project:
  type: book
  output-dir: docs

book:
  title: "Flight Milestones"
  author: "Enrico Spinielli"
  date: "2023-08-01"
  chapters:
    - index.qmd
    - references.qmd

bibliography: bibliography.bib
csl: media/ieee-with-url.csl


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
