project:
  type: book
  output-dir: docs

book:
  title: "Flight Milestones"
  author: "Enrico Spinielli, Quinten Goens"
  date: "2023-10-10"
  chapters:
    - index.qmd
    - references.qmd

bibliography: bibliography.bib
csl: media/ieee-with-url.csl

filters:
  - acronyms

acronyms:
  loa_title: "List of Acronyms"
  include_unused: false
  insert_loa: "end"
  insert_links: true
  id_prefix: "acronyms_"
  sorting: "alphabetical"
  non_existing: "key"
  style: "long-short"
  fromfile:
    - media/acronyms.yml


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
